#! /bin/bash

set -euox pipefail
initials=$(cat initials)
#initials="dp"

if [[ $# -eq 0 ]]; then
    echo "no message for file given"
    exit 1
fi

if [ -f "$1" ]; then
    echo "File found!"
    msg=$(cat "${1}")
else
    echo "send provided message"
    msg="$1"
fi

for i in $initials; do
    pushd "${i}_response"

    echo "$msg" > message.txt
    git add message.txt
    git commit -m "message send $(date)" || true
    git push

    popd
done
